# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hatMatrix <- function(m, length) {
    .Call('additiveRegressionSpline_hatMatrix', PACKAGE = 'additiveRegressionSpline', m, length)
}

cubicSpline <- function(x, knots) {
    .Call('additiveRegressionSpline_cubicSpline', PACKAGE = 'additiveRegressionSpline', x, knots)
}

splineModel <- function(x, knots, y) {
    .Call('additiveRegressionSpline_splineModel', PACKAGE = 'additiveRegressionSpline', x, knots, y)
}

splineModelPenalized <- function(y, x, knots, lambda) {
    .Call('additiveRegressionSpline_splineModelPenalized', PACKAGE = 'additiveRegressionSpline', y, x, knots, lambda)
}

splineModelPMatrix <- function(x, z, knots_x, knots_z) {
    .Call('additiveRegressionSpline_splineModelPMatrix', PACKAGE = 'additiveRegressionSpline', x, z, knots_x, knots_z)
}

splineModelPMatrixFit <- function(y, x, modelMatrix, sX, sZ, lambda_x, lambda_z) {
    .Call('additiveRegressionSpline_splineModelPMatrixFit', PACKAGE = 'additiveRegressionSpline', y, x, modelMatrix, sX, sZ, lambda_x, lambda_z)
}

